-- Firebolt Cloud ClickBench Table Creation
--
-- This script creates the hits table by loading from S3 parquet files
-- using an EXTERNAL TABLE with proper type conversions.
--
-- Note: Replace ${FIREBOLT_DATABASE} with your actual database name.
-- The load_hits.sh script handles this automatically.

DROP TABLE IF EXISTS hits_external;

-- Step 1: Create EXTERNAL TABLE to read parquet files from S3 (quoted mixed case to match parquet)
CREATE EXTERNAL TABLE hits_external (
    "WatchID" BIGINT,
    "JavaEnable" INTEGER,
    "Title" BYTEA,
    "GoodEvent" INTEGER,
    "EventTime" BIGINT,
    "EventDate" INTEGER,
    "CounterID" INTEGER,
    "ClientIP" INTEGER,
    "RegionID" INTEGER,
    "UserID" BIGINT,
    "CounterClass" INTEGER,
    "OS" INTEGER,
    "UserAgent" INTEGER,
    "URL" BYTEA,
    "Referer" BYTEA,
    "IsRefresh" INTEGER,
    "RefererCategoryID" INTEGER,
    "RefererRegionID" INTEGER,
    "URLCategoryID" INTEGER,
    "URLRegionID" INTEGER,
    "ResolutionWidth" INTEGER,
    "ResolutionHeight" INTEGER,
    "ResolutionDepth" INTEGER,
    "FlashMajor" INTEGER,
    "FlashMinor" INTEGER,
    "FlashMinor2" BYTEA,
    "NetMajor" INTEGER,
    "NetMinor" INTEGER,
    "UserAgentMajor" INTEGER,
    "UserAgentMinor" BYTEA,
    "CookieEnable" INTEGER,
    "JavascriptEnable" INTEGER,
    "IsMobile" INTEGER,
    "MobilePhone" INTEGER,
    "MobilePhoneModel" BYTEA,
    "Params" BYTEA,
    "IPNetworkID" INTEGER,
    "TraficSourceID" INTEGER,
    "SearchEngineID" INTEGER,
    "SearchPhrase" BYTEA,
    "AdvEngineID" INTEGER,
    "IsArtifical" INTEGER,
    "WindowClientWidth" INTEGER,
    "WindowClientHeight" INTEGER,
    "ClientTimeZone" INTEGER,
    "ClientEventTime" BIGINT,
    "SilverlightVersion1" INTEGER,
    "SilverlightVersion2" INTEGER,
    "SilverlightVersion3" INTEGER,
    "SilverlightVersion4" INTEGER,
    "PageCharset" BYTEA,
    "CodeVersion" INTEGER,
    "IsLink" INTEGER,
    "IsDownload" INTEGER,
    "IsNotBounce" INTEGER,
    "FUniqID" BIGINT,
    "OriginalURL" BYTEA,
    "HID" INTEGER,
    "IsOldCounter" INTEGER,
    "IsEvent" INTEGER,
    "IsParameter" INTEGER,
    "DontCountHits" INTEGER,
    "WithHash" INTEGER,
    "HitColor" BYTEA,
    "LocalEventTime" BIGINT,
    "Age" INTEGER,
    "Sex" INTEGER,
    "Income" INTEGER,
    "Interests" INTEGER,
    "Robotness" INTEGER,
    "RemoteIP" INTEGER,
    "WindowName" INTEGER,
    "OpenerName" INTEGER,
    "HistoryLength" INTEGER,
    "BrowserLanguage" BYTEA,
    "BrowserCountry" BYTEA,
    "SocialNetwork" BYTEA,
    "SocialAction" BYTEA,
    "HTTPError" INTEGER,
    "SendTiming" INTEGER,
    "DNSTiming" INTEGER,
    "ConnectTiming" INTEGER,
    "ResponseStartTiming" INTEGER,
    "ResponseEndTiming" INTEGER,
    "FetchTiming" INTEGER,
    "SocialSourceNetworkID" INTEGER,
    "SocialSourcePage" BYTEA,
    "ParamPrice" BIGINT,
    "ParamOrderID" BYTEA,
    "ParamCurrency" BYTEA,
    "ParamCurrencyID" INTEGER,
    "OpenstatServiceName" BYTEA,
    "OpenstatCampaignID" BYTEA,
    "OpenstatAdID" BYTEA,
    "OpenstatSourceID" BYTEA,
    "UTMSource" BYTEA,
    "UTMMedium" BYTEA,
    "UTMCampaign" BYTEA,
    "UTMContent" BYTEA,
    "UTMTerm" BYTEA,
    "FromTag" BYTEA,
    "HasGCLID" INTEGER,
    "RefererHash" BIGINT,
    "URLHash" BIGINT,
    "CLID" INTEGER
)
URL = 's3://firebolt-publishing-public/clickbench/'
OBJECT_PATTERN = '*.parquet'
TYPE = (PARQUET);

-- Step 2: Create the hits table with proper schema (lowercase column names)
CREATE TABLE IF NOT EXISTS hits (
    watchid BIGINT NOT NULL,
    javaenable INTEGER NOT NULL,
    title TEXT NOT NULL,
    goodevent INTEGER NOT NULL,
    eventtime TIMESTAMP NOT NULL,
    eventdate DATE NOT NULL,
    counterid INTEGER NOT NULL,
    clientip INTEGER NOT NULL,
    regionid INTEGER NOT NULL,
    userid BIGINT NOT NULL,
    counterclass INTEGER NOT NULL,
    os INTEGER NOT NULL,
    useragent INTEGER NOT NULL,
    url TEXT NOT NULL,
    referer TEXT NOT NULL,
    isrefresh INTEGER NOT NULL,
    referercategoryid INTEGER NOT NULL,
    refererregionid INTEGER NOT NULL,
    urlcategoryid INTEGER NOT NULL,
    urlregionid INTEGER NOT NULL,
    resolutionwidth INTEGER NOT NULL,
    resolutionheight INTEGER NOT NULL,
    resolutiondepth INTEGER NOT NULL,
    flashmajor INTEGER NOT NULL,
    flashminor INTEGER NOT NULL,
    flashminor2 TEXT NOT NULL,
    netmajor INTEGER NOT NULL,
    netminor INTEGER NOT NULL,
    useragentmajor INTEGER NOT NULL,
    useragentminor TEXT NOT NULL,
    cookieenable INTEGER NOT NULL,
    javascriptenable INTEGER NOT NULL,
    ismobile INTEGER NOT NULL,
    mobilephone INTEGER NOT NULL,
    mobilephonemodel TEXT NOT NULL,
    params TEXT NOT NULL,
    ipnetworkid INTEGER NOT NULL,
    traficsourceid INTEGER NOT NULL,
    searchengineid INTEGER NOT NULL,
    searchphrase TEXT NOT NULL,
    advengineid INTEGER NOT NULL,
    isartifical INTEGER NOT NULL,
    windowclientwidth INTEGER NOT NULL,
    windowclientheight INTEGER NOT NULL,
    clienttimezone INTEGER NOT NULL,
    clienteventtime TIMESTAMP NOT NULL,
    silverlightversion1 INTEGER NOT NULL,
    silverlightversion2 INTEGER NOT NULL,
    silverlightversion3 INTEGER NOT NULL,
    silverlightversion4 INTEGER NOT NULL,
    pagecharset TEXT NOT NULL,
    codeversion INTEGER NOT NULL,
    islink INTEGER NOT NULL,
    isdownload INTEGER NOT NULL,
    isnotbounce INTEGER NOT NULL,
    funiqid BIGINT NOT NULL,
    originalurl TEXT NOT NULL,
    hid INTEGER NOT NULL,
    isoldcounter INTEGER NOT NULL,
    isevent INTEGER NOT NULL,
    isparameter INTEGER NOT NULL,
    dontcounthits INTEGER NOT NULL,
    withhash INTEGER NOT NULL,
    hitcolor TEXT NOT NULL,
    localeventtime TIMESTAMP NOT NULL,
    age INTEGER NOT NULL,
    sex INTEGER NOT NULL,
    income INTEGER NOT NULL,
    interests INTEGER NOT NULL,
    robotness INTEGER NOT NULL,
    remoteip INTEGER NOT NULL,
    windowname INTEGER NOT NULL,
    openername INTEGER NOT NULL,
    historylength INTEGER NOT NULL,
    browserlanguage TEXT NOT NULL,
    browsercountry TEXT NOT NULL,
    socialnetwork TEXT NOT NULL,
    socialaction TEXT NOT NULL,
    httperror INTEGER NOT NULL,
    sendtiming INTEGER NOT NULL,
    dnstiming INTEGER NOT NULL,
    connecttiming INTEGER NOT NULL,
    responsestarttiming INTEGER NOT NULL,
    responseendtiming INTEGER NOT NULL,
    fetchtiming INTEGER NOT NULL,
    socialsourcenetworkid INTEGER NOT NULL,
    socialsourcepage TEXT NOT NULL,
    paramprice BIGINT NOT NULL,
    paramorderid TEXT NOT NULL,
    paramcurrency TEXT NOT NULL,
    paramcurrencyid INTEGER NOT NULL,
    openstatservicename TEXT NOT NULL,
    openstatcampaignid TEXT NOT NULL,
    openstatadid TEXT NOT NULL,
    openstatsourceid TEXT NOT NULL,
    utmsource TEXT NOT NULL,
    utmmedium TEXT NOT NULL,
    utmcampaign TEXT NOT NULL,
    utmcontent TEXT NOT NULL,
    utmterm TEXT NOT NULL,
    fromtag TEXT NOT NULL,
    hasgclid INTEGER NOT NULL,
    refererhash BIGINT NOT NULL,
    urlhash BIGINT NOT NULL,
    clid INTEGER NOT NULL
)
PRIMARY INDEX counterid, eventdate, userid, eventtime, watchid;

-- Step 3: INSERT/SELECT with type conversions from external table (UTF-8 encoded text)
INSERT INTO hits
SELECT
    "WatchID",
    "JavaEnable",
    CONVERT_FROM("Title", 'UTF8'),
    "GoodEvent",
    TO_TIMESTAMP("EventTime"),
    TO_DATE('1970-01-01') + "EventDate",
    "CounterID",
    "ClientIP",
    "RegionID",
    "UserID",
    "CounterClass",
    "OS",
    "UserAgent",
    CONVERT_FROM("URL", 'UTF8'),
    CONVERT_FROM("Referer", 'UTF8'),
    "IsRefresh",
    "RefererCategoryID",
    "RefererRegionID",
    "URLCategoryID",
    "URLRegionID",
    "ResolutionWidth",
    "ResolutionHeight",
    "ResolutionDepth",
    "FlashMajor",
    "FlashMinor",
    CONVERT_FROM("FlashMinor2", 'UTF8'),
    "NetMajor",
    "NetMinor",
    "UserAgentMajor",
    CONVERT_FROM("UserAgentMinor", 'UTF8'),
    "CookieEnable",
    "JavascriptEnable",
    "IsMobile",
    "MobilePhone",
    CONVERT_FROM("MobilePhoneModel", 'UTF8'),
    CONVERT_FROM("Params", 'UTF8'),
    "IPNetworkID",
    "TraficSourceID",
    "SearchEngineID",
    CONVERT_FROM("SearchPhrase", 'UTF8'),
    "AdvEngineID",
    "IsArtifical",
    "WindowClientWidth",
    "WindowClientHeight",
    "ClientTimeZone",
    TO_TIMESTAMP("ClientEventTime"),
    "SilverlightVersion1",
    "SilverlightVersion2",
    "SilverlightVersion3",
    "SilverlightVersion4",
    CONVERT_FROM("PageCharset", 'UTF8'),
    "CodeVersion",
    "IsLink",
    "IsDownload",
    "IsNotBounce",
    "FUniqID",
    CONVERT_FROM("OriginalURL", 'UTF8'),
    "HID",
    "IsOldCounter",
    "IsEvent",
    "IsParameter",
    "DontCountHits",
    "WithHash",
    CONVERT_FROM("HitColor", 'UTF8'),
    TO_TIMESTAMP("LocalEventTime"),
    "Age",
    "Sex",
    "Income",
    "Interests",
    "Robotness",
    "RemoteIP",
    "WindowName",
    "OpenerName",
    "HistoryLength",
    CONVERT_FROM("BrowserLanguage", 'UTF8'),
    CONVERT_FROM("BrowserCountry", 'UTF8'),
    CONVERT_FROM("SocialNetwork", 'UTF8'),
    CONVERT_FROM("SocialAction", 'UTF8'),
    "HTTPError",
    "SendTiming",
    "DNSTiming",
    "ConnectTiming",
    "ResponseStartTiming",
    "ResponseEndTiming",
    "FetchTiming",
    "SocialSourceNetworkID",
    CONVERT_FROM("SocialSourcePage", 'UTF8'),
    "ParamPrice",
    CONVERT_FROM("ParamOrderID", 'UTF8'),
    CONVERT_FROM("ParamCurrency", 'UTF8'),
    "ParamCurrencyID",
    CONVERT_FROM("OpenstatServiceName", 'UTF8'),
    CONVERT_FROM("OpenstatCampaignID", 'UTF8'),
    CONVERT_FROM("OpenstatAdID", 'UTF8'),
    CONVERT_FROM("OpenstatSourceID", 'UTF8'),
    CONVERT_FROM("UTMSource", 'UTF8'),
    CONVERT_FROM("UTMMedium", 'UTF8'),
    CONVERT_FROM("UTMCampaign", 'UTF8'),
    CONVERT_FROM("UTMContent", 'UTF8'),
    CONVERT_FROM("UTMTerm", 'UTF8'),
    CONVERT_FROM("FromTag", 'UTF8'),
    "HasGCLID",
    "RefererHash",
    "URLHash",
    "CLID"
FROM hits_external;

-- Step 4: Drop external table
DROP TABLE IF EXISTS hits_external;
